"""Add nursery station fields to crops table

Revision ID: b1f075ab897b
Revises: 8b57bcd12765
Create Date: 2025-07-10 03:20:54.451254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f075ab897b'
down_revision: Union[str, None] = '8b57bcd12765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('tray_id', sa.Integer(), nullable=True))
    op.add_column('crops', sa.Column('row', sa.Integer(), nullable=True))
    op.add_column('crops', sa.Column('column', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_crops_tray_id'), 'crops', ['tray_id'], unique=False)
    op.create_foreign_key(None, 'crops', 'trays', ['tray_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crops', type_='foreignkey')
    op.drop_index(op.f('ix_crops_tray_id'), table_name='crops')
    op.drop_column('crops', 'column')
    op.drop_column('crops', 'row')
    op.drop_column('crops', 'tray_id')
    # ### end Alembic commands ###
