"""Add seed_type table for page2

Revision ID: 2a31ce608337
Revises: 1a31ce608336
Create Date: 2024-12-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a31ce608337'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seedtype',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('variety', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Insert mock data for seed types
    op.execute("""
        INSERT INTO seedtype (id, name, variety, supplier) VALUES
        ('seed-001', 'Someroots', 'Standard', 'BioCrop'),
        ('seed-002', 'Sunflower', 'Giant', 'SeedPro'),
        ('seed-003', 'Basil', 'Sweet', 'HerbGarden'),
        ('seed-004', 'Lettuce', 'Romaine', 'GreenLeaf'),
        ('seed-005', 'Kale', 'Curly', 'Nutrifoods'),
        ('seed-006', 'Spinach', 'Baby', 'GreenLeaf'),
        ('seed-007', 'Arugula', 'Wild', 'HerbGarden'),
        ('seed-008', 'Microgreens', 'Mixed', 'SproutLife')
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seedtype')
    # ### end Alembic commands ###